name: Build application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14.x"

    - name: Install dependencies
      run: |
        echo "Installing dependencies â¬"
        npm ci
        ls
        echo $PATH

    - name: Build application
      run: |
        echo "Building application ğŸ‘·"
        npm run build --if-present
        echo "Building is complete âœ…"

    - name: Run tests
      run: |
        echo "Starting tests ğŸ§ª"
        npm run test:unit
        echo "Tests have passed âœ… :D"
